# Generated by Django 5.0.2 on 2024-03-27 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='Producer_images')),
                ('slug', models.SlugField(blank=True, max_length=120, primary_key=True, serialize=False)),
                ('ceo', models.CharField(blank=True, max_length=101)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=25, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('title', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='airplane_images')),
                ('year_publ', models.CharField(max_length=4)),
                ('slug', models.SlugField(blank=True, max_length=80, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('archive', 'Archived'), ('avail', 'Available')], max_length=9)),
                ('airplane', models.FileField(blank=True, upload_to='airplane_files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Airplane_producers', to='airplane.producer')),
                ('type', models.ManyToManyField(related_name='airplane_type', to='airplane.type')),
            ],
            options={
                'verbose_name': 'Airplane',
                'verbose_name_plural': 'Airplanes',
            },
        ),
    ]
